apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: event-producer-tekton-trigger-binding
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: k8s-namespace
      value: quarkus-producer
    - name: git-url
      value: "https://github.com/$(body.repository.full_name)"
