apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kafka-event-producer-maven-pipeline
spec:
  workspaces:
  - name: quarkus-maven-repo

  resources:
  - name: kafka-event-producer-github-repo
    type: git
  - name: output-runnable-image
    type: image

  params:
    - name: dockerfilePath
      type: string
      description: Path containing the Dockerfile for the final image
      default: "src/main/docker"

  tasks:
  - name: clone
    taskRef:
      name: quarkus-clone-task
    resources:
      inputs:
      - name: source
        resource: kafka-event-producer-github-repo
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo

  - name: build
    taskRef:
      name: quarkus-maven-task
    runAfter: ["clone"]
    params:
    - name: GOALS
      value: ["-Dmaven.repo.local=$(workspaces.maven-repo.path)", "-DskipTests=true", "compile"]
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo

  - name: test
    taskRef:
      name: quarkus-maven-task
    runAfter: ["build"]
    params:
    - name: GOALS
      value: ["-Dmaven.repo.local=$(workspaces.maven-repo.path)", "test"]
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo

  - name: jacoco
    taskRef:
      name: quarkus-maven-task
    runAfter: ["test"]
    params:
    - name: GOALS
      value: ["-Dmaven.repo.local=$(workspaces.maven-repo.path)", "jacoco:report"]
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo

  - name: package
    taskRef:
      name: quarkus-maven-task
    runAfter: ["test"]
    params:
    - name: GOALS
      value: ["-Dmaven.repo.local=$(workspaces.maven-repo.path)", "-DskipTests=true", "package"]
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo

  - name: build-container-image
    taskRef:
      name: quarkus-build-task
    runAfter: ["package"]
    params:
      - name: TLS_VERIFY
        value: "false"
      - name: dockerfilePath
        value: "src/main/docker"
    resources:
      outputs:
      - name: image
        resource: output-runnable-image
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo

  finally:
  - name: clean-workspace
    taskRef:
      name: cleanup-workspace
    workspaces:
    - name: maven-repo
      workspace: quarkus-maven-repo